tested fail

diff --git a/.github/workflows/reuse-build-revealmd.yml b/.github/workflows/reuse-build-revealmd.yml
--- a/.github/workflows/reuse-build-revealmd.yml
+++ b/.github/workflows/reuse-build-revealmd.yml
@@ -42,29 +42,27 @@ jobs:
       - name: Clone Reveal-MD
         run: git clone https://github.com/webpro/reveal-md.git
 
-      - name: Copy markdown files to Reveal-MD
-        run: rsync -avh markdown reveal-md
-
       - name: Install Reveal-MD
         run: npm ci
 
       - name: Fail test
         run: rsync slidify.spec.js reveal-md/test
 
-      #- name: Run tests from Reveal-MD
-      #  run: npm run test
+      # If this tests fail the NPM error will fail this job
+      - name: Run tests from Reveal-MD
+        run: npm run test
 
       - name: GitHub Step Summary for Test
         run: |
           echo "### Test Summary" >> $GITHUB_STEP_SUMMARY
           echo "$(npm run test)" >> $GITHUB_STEP_SUMMARY
 
-      - name: Evaluate Test Results
-        run: |
-          if [[ "$(npm run test)" == *"failed"* ]]; then
-            echo "REVEAL-MD TEST FAILED"
-            exit 1
-          fi
+      #- name: Evaluate Test Results
+      #  run: |
+      #    if [[ "$(npm run test)" == *"failed"* ]]; then
+      #      echo "REVEAL-MD TEST FAILED"
+      #      exit 1
+      #    fi
 
       - name: Run Reveal-MD build
         run: npm run build
